const { body, param } = require("express-validator");

// Upload Report Validator
const uploadReportValidator = [
  body("title")
    .notEmpty()
    .withMessage("Report title is required")
    .trim()
    .isLength({ min: 3, max: 200 })
    .withMessage("Title must be between 3 and 200 characters"),

  body("reportType")
    .notEmpty()
    .withMessage("Report type is required")
    .isIn([
      "lab-result",
      "imaging",
      "prescription",
      "discharge-summary",
      "other",
    ])
    .withMessage("Invalid report type"),

  // fileUrl is generated by Cloudinary in the controller
  // so it should NOT be validated here.

  body("fileName")
    .optional({ values: "falsy" })
    .trim(),

  body("fileSize")
    .optional({ values: "falsy" })
    .isNumeric()
    .withMessage("File size must be a number"),

  body("mimeType")
    .optional({ values: "falsy" })
    .trim(),

  body("description")
    .optional()
    .trim()
    .isLength({ max: 500 })
    .withMessage("Description cannot exceed 500 characters"),

  body("doctor")
    .optional({ values: "falsy" })
    .isMongoId()
    .withMessage("Invalid doctor ID"),

  body("reportDate")
    .optional({ values: "falsy" })
    .isISO8601()
    .withMessage("Invalid report date format"),

  body("isConfidential")
    .optional({ values: "falsy" })
    .isBoolean()
    .withMessage("isConfidential must be a boolean"),

  body("tags")
    .optional({ values: "falsy" })
    .custom((value) => {
      if (Array.isArray(value)) return true;
      if (typeof value === "string") return true;
      throw new Error("Tags must be an array or comma-separated string");
    }),
];

// Update Report Validator
const updateReportValidator = [
  param("id")
    .isMongoId()
    .withMessage("Invalid report ID"),

  body("title")
    .optional()
    .trim()
    .isLength({ min: 3, max: 200 })
    .withMessage("Title must be between 3 and 200 characters"),

  body("reportType")
    .optional()
    .isIn([
      "lab-result",
      "imaging",
      "prescription",
      "discharge-summary",
      "other",
    ])
    .withMessage("Invalid report type"),

  body("description")
    .optional()
    .trim()
    .isLength({ max: 500 })
    .withMessage("Description cannot exceed 500 characters"),

  body("doctor")
    .optional({ values: "falsy" })
    .isMongoId()
    .withMessage("Invalid doctor ID"),

  body("reportDate")
    .optional({ values: "falsy" })
    .isISO8601()
    .withMessage("Invalid report date format"),

  body("isConfidential")
    .optional({ values: "falsy" })
    .isBoolean()
    .withMessage("isConfidential must be a boolean"),

  body("tags")
    .optional({ values: "falsy" })
    .custom((value) => {
      if (Array.isArray(value)) return true;
      if (typeof value === "string") return true;
      throw new Error("Tags must be an array or comma-separated string");
    }),
];

// Report ID Validator
const reportIdValidator = [
  param("id")
    .isMongoId()
    .withMessage("Invalid report ID"),
];

module.exports = {
  uploadReportValidator,
  updateReportValidator,
  reportIdValidator,
};
